version: "3.9"

services:
  web:
    image: ${CHAT_API_IMAGE:-ghcr.io/example/chat_api:latest}
    env_file:
      - .env.production
    ports:
      - "${CHAT_API_PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  db:
    image: postgres:16-alpine
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-chat_api_production}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres-data:
  redis-data:
