default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "chat_api_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "chat_api_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "chat_api_production") %>
  url: <%= ENV["DATABASE_URL"] %>
